{% set name = "bgzip" %}
{% set version = "0.4.0" %}


package:
  name: py-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bgzip-{{ version }}.tar.gz
  sha256: 2562202a99b0cff1777d051cd3ed7ffa9a568ff8486f922935808e1a0478f01c

build:
  number: 5
  script:
    - export BUILD_WITH_CYTHON=1  # [not win]
    - set BUILD_WITH_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - cython
    - setuptools
    - pip
    - python
    - zlib
  run:
    - python

test:
  imports:
    - bgzip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xbrianh/bgzip.git
  summary: Utilities working with blocked gzip streams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dpryan79
